name: MyAuth
main: MyAuth\MyAuth
version: "1.3-dev1"
api: ["3.0.0-ALPHA1", "3.0.0-ALPHA2", "3.0.0-ALPHA3", "3.0.0-ALPHA4", "3.0.0-ALPHA5", "3.0.0-ALPHA6", "3.0.0-ALPHA7"]
load: STARTUP
author: SuperPuperSteve
description: Simple authentication plugin

commands:
 register:
  aliases: ['reg']
  description: Register an account
 login:
  aliases: ['l']
  description: Login into an account
 unregister:
  description: Unregister an account
 changepassword:
  aliases: ['passwd', 'chp']
  description: Changes password
 logout:
  description: Log out from an account
 myadmin:
  description: MyAuth admin

permissions:
 myauth:
  description: MyAuth managment global permission
  default: op
  
  children:
   myauth.myadmin:
    description: MyAuth admin permission
    default: op
